### ISSUE TITLE
hp-tcg-v0.1-release.exe broke my Windows 10

### ISSUE THREAD

**Issue by MaximeAnsquer** [StefanoFiumara/Harry-Potter-Unity#91] opened 2017-02-01 10:53 UTC
After launching hp-tcg-v0.1-release.exe, choosing the resolution and hitting play, I had a Windows Blue Screen of Death with the error code " DPC_WATCHDOG_VIOLATION ".

Then everytime I started Windows, after 5 minutes it would display the same Blue Screen of Death or another one with the error code : SYSTEM_THREAD_EXCEPTION_NOT_HANDLED ".

At some point I was lucky and had enough time to restore to a restore point previous to the execution of  hp-tcg-v0.1-release.exe, but the BSOF kept happening.

I tried to reset windows but it and error occured during the reset. I managed to reset windows from a bootable USB drive and I hope everything is solved now...

**Comment by StefanoFiumara** [comment] 2017-02-02 00:49
I'm not seeing this issue on my end :/

In either case, a new release is overdue since the photon API key has changed and the 1.0 release no longer works.

I've got a ton of new cards implemented as well as a UI overhaul, but there are a few things missing (like a game end screen) that are preventing me from making a new release.

You can try cloning the repo and running the more updated version if you like, it should be much more stable.

**Comment by MaximeAnsquer** [comment] 2017-02-02 10:18
I tried cloning the repo and running the project, this time I had a new bleu screen: " video scheduler internal error ". Luckily Windows seems not to be dead this time.

**Comment by StefanoFiumara** [comment] 2017-04-17 19:03
Hi Maxime,

I'm going to close this issue since I am unable to reproduce what you are seeing.

I plan on making a new release soon, look forward to that and maybe you won't be seeing the problem any longer.

**Closed by StefanoFiumara** 2017-04-17 19:03 UTC
